baseURL = 'https://nothingness0db.github.io/lyu0802'
languageCode = 'zh-CN'
title = 'lyu0802'
theme = 'PaperMod'

[params]
  author = 'lyu0802'
  description = '随便写写'
  ShowReadingTime = true
  ShowShareButtons = false
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  ShowToc = true
  
  [params.profileMode]
    enabled = true
    title = 'lyu0802'
    subtitle = '随便写写'
    imageUrl = ''
    imageTitle = ''
    
    [[params.profileMode.buttons]]
      name = '归档'
      url = 'posts'
    [[params.profileMode.buttons]]
      name = '关于'
      url = 'about'

[menu]
  [[menu.main]]
    identifier = 'posts'
    name = '日报'
    url = '/posts/'
    weight = 10
  [[menu.main]]
    identifier = 'about'
    name = '关于'
    url = '/about/'
    weight = 20
